# Generated by Django 3.2.22 on 2023-10-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, max_length=3)),
                ('biography', models.TextField(blank=True)),
                ('owned_cars', models.IntegerField(blank=True)),
                ('issues_posted', models.IntegerField(blank=True)),
                ('issues_solved', models.IntegerField(blank=True)),
                ('image', models.ImageField(default='../default_profile', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issues_solved'],
            },
        ),
    ]
