# Generated by Django 3.2.22 on 2023-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_ponhew', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issues_posted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issues_solved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owned_cars',
            field=models.IntegerField(),
        ),
    ]
