# Generated by Django 3.2.22 on 2023-10-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_age_profile_birth_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_year',
            new_name='year_of_birth',
        ),
    ]
