# Generated by Django 3.2.22 on 2023-10-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_year_of_birth_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='year_of_birth',
        ),
    ]
