# Generated by Django 3.2.22 on 2023-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_age_profile_year_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_of_birth',
            new_name='fuckdig',
        ),
    ]
