# Generated by Django 3.2.22 on 2023-10-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_year_of_birth_profile_fuckdig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fuckdig',
            new_name='age',
        ),
    ]
