# Generated by Django 3.2.22 on 2023-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231017_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
