# Generated by Django 3.2.22 on 2023-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_issue_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq', null=True, upload_to='images/'),
        ),
    ]
