# Generated by Django 3.2.22 on 2023-10-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followingcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowingComment',
        ),
    ]
